on:
  schedule:
    - cron: "30 2,6,9 * * *"
  push:
    branches: [ main ]

jobs:
  update_numbers:
    name: Updates the counts from source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v2
        with:
          path: main
          fetch-depth: 0
      - name: Checkout source data repo
        uses: actions/checkout@v2
        with:
          repository: CSSEGISandData/COVID-19
          path: data
      - name: Install Dependencies
        run: |
          cd main
          npm install
      - name: Creating JSON from CSV
        uses: ./main/
        id: creating
      - name: Commit files
        run: |
          cd main
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update JSON" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: main
